### ISSUE TITLE
Setting state in Home component

### ISSUE THREAD

**Issue by sventies** [tylermcginnis/React-Router-Course-Project#1]
Hi Tyler, 

Thanks for your great tutorial. I'm not sure where to ask questions about it so I'll ask it here, let me know if there is a better / other place for it.

In your video about the Home component, you get TeamNames and then you set the state:
Branch: home
File: React-Router-Course-Project/src/components/Home.js

From line 10:
```javascript
  componentDidMount () {
    getTeamNames()
      .then((teamNames) => this.setState(() => ({
        teamNames
      })))
  }
```

Why are you initiating a new function, instead of immediately setting the state to teamNames, like this:
```javascript
  componentDidMount() {
    getTeamNames()
      .then((teamNames) => this.setState({ teamNames }))
  }
```

**Comment by tylermcginnis** [comment]
Hey good question (and sorry just now seeing this). The answer is just preference. I like to minimize what I have to think about. When you use object setState, you first need to figure out if you're setting the new state based on the previous state. If you always use functional setState, you never have to think about it.
